import dns from 'dns'
dns.setDefaultResultOrder('ipv4first')

import { Poppins } from "next/font/google";
import "./globals.css";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

    const getPoppins = Poppins({
      variable: "--font-poppins",
      subsets: ["latin"],
      weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    });

export const metadata = {
  title: "Dragon News App",
  description: "Generated by The Dragon News app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light" className={`${getPoppins.variable}} antialiased`}>
      <body className="max-w-300 mx-auto">
        <main>
          {children}
        </main>
        <ToastContainer position="top-center" />
      </body>
    </html>
  );
}
