import { Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

export const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "The Dragon News",
  description: "Generated by Dragon News app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" 
    data-theme="light"
    className={`${poppins.variable} antialiased`}>
      <body className="max-w-310 mx-auto">
        
        <main>
          {children}
        </main>
        <ToastContainer position="top-center" />
      </body>
    </html>
  );
}
