import Image from 'next/image';
import Link from 'next/link';
import React from 'react';
import { FaArrowLeft } from 'react-icons/fa';
export const metadata = {
  title: "Dragon News Details",
  description: "Generated by The Dragon News app",
};
const NewsDetailsPage = async ({ params }) => {
  const { newsDetailsId } = await params;
  const res = await fetch(`https://openapi.programming-hero.com/api/news/${newsDetailsId}`);
  const data = await res.json();
  const details = data.data[0];

  return (
    <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 my-10">
      {/* Title Section */}
      <h2 className="text-2xl font-bold text-gray-800 mb-6">Dragon News</h2>

      <div className="bg-white border rounded-lg p-5 lg:p-8 shadow-sm">
        {/* News Image */}
        <div className="relative w-full h-[250px] md:h-[450px] mb-8">
          <Image
            src={details.image_url}
            fill
            className="rounded-lg object-cover"
            alt="News Details"
            priority
          />
        </div>

        {/* News Title */}
        <h1 className="text-2xl md:text-3xl font-extrabold text-gray-800 mb-5 leading-tight">
          {details.title}
        </h1>

        {/* Details Text */}
        <div className="text-gray-600 leading-relaxed text-base md:text-lg mb-8 whitespace-pre-line">
          {details.details}
        </div>

        {/* Action Button */}
        <div className="mt-10">
          <Link href={`/category/${details.category_id}`}>
            <button className="flex cursor-pointer items-center gap-2 bg-[#D72050] hover:bg-[#b51b43] text-white px-6 py-3 rounded-none transition-all duration-300 font-semibold">
              <FaArrowLeft className="text-sm" />
              All news in this category
            </button>
          </Link>
        </div>
      </div>
    </div>
  );
};

export default NewsDetailsPage;